<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shweta-PC" failures="8" tests="68" name="dsAlgo_TestClasses.Array_TestClass" time="457.096" errors="9" timestamp="2025-03-13T18:05:09 EDT" skipped="20">
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="validLoginDataBase" time="7.013"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="LogIn" time="4.840"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="arrayDropdownList" time="5.316"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="ArrayGetStarted" time="4.952"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="arrayDisplayTitle" time="6.796"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="ArrayInPythonLink" time="5.424"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="NavigateTOArrayInPython" time="5.517"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="validateArrayInPython" time="5.874"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="ArrayInPythonTryHere" time="5.624"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="ArrayInPythonTryHereBtn" time="6.157"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="ValidateArrayInPythonTryHereBtn" time="6.539"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TestArrayInPythonCode" time="2.057">
    <error message="
Method public void dsAlgo_TestClasses.Array_TestClass.TestArrayInPythonCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ArrayExcelData in class dsAlgo_Utilities.DataProvider_Class" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void dsAlgo_TestClasses.Array_TestClass.TestArrayInPythonCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ArrayExcelData in class dsAlgo_Utilities.DataProvider_Class
at org.testng.internal.Parameters.findDataProvider(Parameters.java:532)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- TestArrayInPythonCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="ArrayUsingList" time="5.984"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="validateArrayUsingListpage" time="5.666"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TryHereArrayUsingbtn" time="6.200"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TestArrayUsingListCode" time="2.085">
    <error message="
Method public void dsAlgo_TestClasses.Array_TestClass.TestArrayUsingListCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ArrayExcelData in class dsAlgo_Utilities.DataProvider_Class" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void dsAlgo_TestClasses.Array_TestClass.TestArrayUsingListCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ArrayExcelData in class dsAlgo_Utilities.DataProvider_Class
at org.testng.internal.Parameters.findDataProvider(Parameters.java:532)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- TestArrayUsingListCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="BasicOperationList" time="5.697"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="NavigateToBasicOperationListPage" time="5.278"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TryHereBasicOprList" time="6.290"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TestForBasicOprListCode" time="2.022">
    <error message="
Method public void dsAlgo_TestClasses.Array_TestClass.TestForBasicOprListCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ArrayExcelData in class dsAlgo_Utilities.DataProvider_Class" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void dsAlgo_TestClasses.Array_TestClass.TestForBasicOprListCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ArrayExcelData in class dsAlgo_Utilities.DataProvider_Class
at org.testng.internal.Parameters.findDataProvider(Parameters.java:532)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- TestForBasicOprListCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="BasicOprListRunBtnWithoutCode" time="6.288">
    <skipped/>
  </testcase> <!-- BasicOprListRunBtnWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="BasicOprListRunBtnWithoutCode" time="6.563">
    <failure message="expected [Enter code in text area] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Enter code in text area] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgo_TestClasses.Array_TestClass.BasicOprListRunBtnWithoutCode(Array_TestClass.java:179)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- BasicOprListRunBtnWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="BasicOprListRunBtnWithoutCode" time="6.407">
    <skipped/>
  </testcase> <!-- BasicOprListRunBtnWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="ApplicationOfArray" time="6.319"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="NAvigateToApplicationOfArray" time="6.098"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TryHereApplicationOfArray" time="7.399"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TestApplicationOfArrayCode" time="1.876">
    <error message="
Method public void dsAlgo_TestClasses.Array_TestClass.TestApplicationOfArrayCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ArrayExcelData in class dsAlgo_Utilities.DataProvider_Class" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void dsAlgo_TestClasses.Array_TestClass.TestApplicationOfArrayCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ArrayExcelData in class dsAlgo_Utilities.DataProvider_Class
at org.testng.internal.Parameters.findDataProvider(Parameters.java:532)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- TestApplicationOfArrayCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="ApplicationOfArrayRunBtnWithoutCode" time="6.687">
    <failure message="expected [Enter code in text area] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Enter code in text area] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgo_TestClasses.Array_TestClass.ApplicationOfArrayRunBtnWithoutCode(Array_TestClass.java:218)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- ApplicationOfArrayRunBtnWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="ApplicationOfArrayRunBtnWithoutCode" time="6.809">
    <skipped/>
  </testcase> <!-- ApplicationOfArrayRunBtnWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="ApplicationOfArrayRunBtnWithoutCode" time="6.730">
    <skipped/>
  </testcase> <!-- ApplicationOfArrayRunBtnWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="PracticeQuestionLink" time="6.177"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="NavigateToPracticeQuestion" time="6.002"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="searchTheArrayPage" time="7.031"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="NavigateToSearchTheArrayTextArea" time="6.616"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TestSearchArrayCode" time="2.097">
    <error message="
Method public void dsAlgo_TestClasses.Array_TestClass.TestSearchArrayCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ArrayExcelData in class dsAlgo_Utilities.DataProvider_Class" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void dsAlgo_TestClasses.Array_TestClass.TestSearchArrayCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ArrayExcelData in class dsAlgo_Utilities.DataProvider_Class
at org.testng.internal.Parameters.findDataProvider(Parameters.java:532)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- TestSearchArrayCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSearchArrayRunBtnWithoutCode" time="7.713">
    <skipped/>
  </testcase> <!-- clickSearchArrayRunBtnWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSearchArrayRunBtnWithoutCode" time="8.786">
    <skipped/>
  </testcase> <!-- clickSearchArrayRunBtnWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSearchArrayRunBtnWithoutCode" time="7.490">
    <failure message="expected [Enter valid code] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Enter valid code] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgo_TestClasses.Array_TestClass.clickSearchArrayRunBtnWithoutCode(Array_TestClass.java:264)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickSearchArrayRunBtnWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnSearchArrayWithoutCode" time="12.857">
    <skipped/>
  </testcase> <!-- clickSubmitBtnSearchArrayWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnSearchArrayWithoutCode" time="12.685">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;link text&quot;,&quot;selector&quot;:&quot;Sign in&quot;}
  (Session info: chrome=131.0.6778.204)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &#039;4.29.0&#039;, revision: &#039;5fc1ec94cb&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;23.0.1&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [6b8819027b9e14d93acb1878a2f1af69, findElement {value=Sign in, using=link text}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.204, chrome: {chromedriverVersion: 131.0.6778.264 (2d05e315153..., userDataDir: C:\Users\mahaj\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:56346}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:56346/devtoo..., se:cdpVersion: 131.0.6778.204, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6b8819027b9e14d93acb1878a2f1af69" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"link text","selector":"Sign in"}
  (Session info: chrome=131.0.6778.204)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.29.0', revision: '5fc1ec94cb'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [6b8819027b9e14d93acb1878a2f1af69, findElement {value=Sign in, using=link text}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.204, chrome: {chromedriverVersion: 131.0.6778.264 (2d05e315153..., userDataDir: C:\Users\mahaj\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:56346}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:56346/devtoo..., se:cdpVersion: 131.0.6778.204, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6b8819027b9e14d93acb1878a2f1af69
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy21.click(Unknown Source)
at dsAlgo_PageFactory.Login_PageFactory.signInClick(Login_PageFactory.java:32)
at dsAlgo_BaseClass.BaseClass.validLoginDataBase(BaseClass.java:60)
at dsAlgo_TestClasses.Array_TestClass.LogIn(Array_TestClass.java:38)
at dsAlgo_TestClasses.Array_TestClass.ArrayGetStarted(Array_TestClass.java:51)
at dsAlgo_TestClasses.Array_TestClass.BasicOperationList(Array_TestClass.java:147)
at dsAlgo_TestClasses.Array_TestClass.ApplicationOfArray(Array_TestClass.java:186)
at dsAlgo_TestClasses.Array_TestClass.PracticeQuestionLink(Array_TestClass.java:223)
at dsAlgo_TestClasses.Array_TestClass.searchTheArrayPage(Array_TestClass.java:237)
at dsAlgo_TestClasses.Array_TestClass.clickSubmitBtnSearchArrayWithoutCode(Array_TestClass.java:271)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- clickSubmitBtnSearchArrayWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnSearchArrayWithoutCode" time="12.670">
    <skipped/>
  </testcase> <!-- clickSubmitBtnSearchArrayWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="MaxConsOne" time="6.859"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="NavigateToMaxConsOneTextArea" time="7.469"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TestMaxConsOneCode" time="1.835">
    <error message="
Method public void dsAlgo_TestClasses.Array_TestClass.TestMaxConsOneCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ExcelDataMaxConsOne in class dsAlgo_Utilities.DataProvider_Class" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void dsAlgo_TestClasses.Array_TestClass.TestMaxConsOneCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ExcelDataMaxConsOne in class dsAlgo_Utilities.DataProvider_Class
at org.testng.internal.Parameters.findDataProvider(Parameters.java:532)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- TestMaxConsOneCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickRunBtnMaxConsOneWithoutCode" time="7.156">
    <skipped/>
  </testcase> <!-- clickRunBtnMaxConsOneWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickRunBtnMaxConsOneWithoutCode" time="8.299">
    <skipped/>
  </testcase> <!-- clickRunBtnMaxConsOneWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickRunBtnMaxConsOneWithoutCode" time="6.868">
    <failure message="expected [Enter valid code] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Enter valid code] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgo_TestClasses.Array_TestClass.clickRunBtnMaxConsOneWithoutCode(Array_TestClass.java:307)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickRunBtnMaxConsOneWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnMaxConsOneWithoutCode" time="7.738">
    <failure message="expected [Error occurred during submission] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgo_TestClasses.Array_TestClass.clickSubmitBtnMaxConsOneWithoutCode(Array_TestClass.java:315)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickSubmitBtnMaxConsOneWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnMaxConsOneWithoutCode" time="7.470">
    <skipped/>
  </testcase> <!-- clickSubmitBtnMaxConsOneWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnMaxConsOneWithoutCode" time="7.571">
    <skipped/>
  </testcase> <!-- clickSubmitBtnMaxConsOneWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="EvenNumDigits" time="10.825"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="NavigateToEvenNumDigits" time="11.577"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TestEvenNumDigitsCode" time="1.983">
    <error message="
Method public void dsAlgo_TestClasses.Array_TestClass.TestEvenNumDigitsCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ExcelDataMaxConsOne in class dsAlgo_Utilities.DataProvider_Class" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void dsAlgo_TestClasses.Array_TestClass.TestEvenNumDigitsCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ExcelDataMaxConsOne in class dsAlgo_Utilities.DataProvider_Class
at org.testng.internal.Parameters.findDataProvider(Parameters.java:532)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- TestEvenNumDigitsCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickRunBtnEvenNumDigitsWithoutCode" time="11.426">
    <skipped/>
  </testcase> <!-- clickRunBtnEvenNumDigitsWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickRunBtnEvenNumDigitsWithoutCode" time="11.303">
    <skipped/>
  </testcase> <!-- clickRunBtnEvenNumDigitsWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickRunBtnEvenNumDigitsWithoutCode" time="11.647">
    <failure message="expected [Enter valid code] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Enter valid code] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgo_TestClasses.Array_TestClass.clickRunBtnEvenNumDigitsWithoutCode(Array_TestClass.java:348)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickRunBtnEvenNumDigitsWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnEvenNumDigitsWithoutCode" time="11.541">
    <skipped/>
  </testcase> <!-- clickSubmitBtnEvenNumDigitsWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnEvenNumDigitsWithoutCode" time="11.569">
    <skipped/>
  </testcase> <!-- clickSubmitBtnEvenNumDigitsWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnEvenNumDigitsWithoutCode" time="11.633"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="SortedArray" time="7.472"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="NavigateToSortedArray" time="5.321"/>
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="TestSortedArrayCode" time="0.000">
    <error message="
Method public void dsAlgo_TestClasses.Array_TestClass.TestSortedArrayCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ExcelDataSortedArray in class dsAlgo_Utilities.DataProvider_Class" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void dsAlgo_TestClasses.Array_TestClass.TestSortedArrayCode(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : ExcelDataSortedArray in class dsAlgo_Utilities.DataProvider_Class
at org.testng.internal.Parameters.findDataProvider(Parameters.java:532)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- TestSortedArrayCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickRunBtnSortedArrayWithoutCode" time="5.340">
    <skipped/>
  </testcase> <!-- clickRunBtnSortedArrayWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickRunBtnSortedArrayWithoutCode" time="5.287">
    <failure message="expected [Enter valid code] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Enter valid code] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgo_TestClasses.Array_TestClass.clickRunBtnSortedArrayWithoutCode(Array_TestClass.java:390)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickRunBtnSortedArrayWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickRunBtnSortedArrayWithoutCode" time="5.774">
    <skipped/>
  </testcase> <!-- clickRunBtnSortedArrayWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnSortedArrayWithoutCode" time="5.578">
    <skipped/>
  </testcase> <!-- clickSubmitBtnSortedArrayWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnSortedArrayWithoutCode" time="5.436">
    <failure message="expected [Error occurred during submission] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgo_TestClasses.Array_TestClass.clickSubmitBtnSortedArrayWithoutCode(Array_TestClass.java:397)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickSubmitBtnSortedArrayWithoutCode -->
  <testcase classname="dsAlgo_TestClasses.Array_TestClass" name="clickSubmitBtnSortedArrayWithoutCode" time="5.488">
    <skipped/>
  </testcase> <!-- clickSubmitBtnSortedArrayWithoutCode -->
</testsuite> <!-- dsAlgo_TestClasses.Array_TestClass -->
